# -*- coding: utf-8 -*-
"""classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H7mojEp6wUV06pMrB85tg1suMQ0PTYaf
"""

import pandas as pd
data = pd.read_csv("/content/penguins_classification.csv")
data.head()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix,f1_score,classification_report

#handling null values
print(data.isnull().sum())
data.dropna(inplace=True)

#eda
data.shape
data.dtypes
data.columns
data.info()
data.describe()
data.duplicated().sum()

import matplotlib.pyplot as plt
import seaborn as sns
plt.figure(figsize=(18, 5))
plt.subplot(1, 3, 1)
sns.histplot(data=data, x='island', kde=True)
plt.subplot(1, 3, 2)
sns.histplot(data=data, x='body_mass_g', kde=True)

#conerting the categorical columns into numerical columns
Le = LabelEncoder()
cat = ['species','island']
data[cat] = data[cat].apply(Le.fit_transform)
data

plt.tight_layout()
plt.show()


#heat map usage
plt.figure(figsize=(10,6))
sns.heatmap(data.corr(),annot=True)

#Outliers handling
from scipy.stats import zscore
zscores = zscore(data)
abs = np.abs(zscores)
f = (abs > 3).all(axis=1)
clean = data[~f]
cl = pd.DataFrame(clean)
print(cl.shape,data.shape)


X = data.drop(['species'],axis=1)
y = data['species']

#splitting data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.ensemble import RandomForestClassifier
clf=RandomForestClassifier()
feat=clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)

#performance metrics

print("Classification report \n",classification_report(y_test,y_pred))
print("\nConfusion matrix \n",confusion_matrix(y_test,y_pred))
print("\nAccuracy score \n",accuracy_score(y_test,y_pred))

"""This Model is providing the classification of species of penguins with an accuracy of 1.0 which can be furtherly used for their health studies and also ecological studies."""

data.head()