# -*- coding: utf-8 -*-
"""Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1goPV6IZM-fSV232kDuqS3EhgHIS34ugE
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt
import seaborn as sns

data=pd.read_csv('/content/Fare prediction.csv')
data.head()
#handling null values
data.isnull().sum()
#shape of data
data.shape

#EDA
data.info()
data.describe()
data.columns
data.dtypes

#converting categorical columns into numerical columns
label_encoder = LabelEncoder()
data['key'] = label_encoder.fit_transform(data[['key']])
data['pickup_datetime'] = label_encoder.fit_transform(data[['pickup_datetime']])

#plotting graphs inorder to display relations


# sns.pairplot(data)
# plt.show()

#heatmap usage
plt.figure(figsize=(10, 8))
sns.heatmap(data.corr(), annot=True, cmap='coolwarm', fmt='.2f')
plt.title('Correlation Heatmap')
plt.show()

#outliers detection
Q1 = data.quantile(0.25)
Q3 = data.quantile(0.75)
IQR = Q3 - Q1
data = data[~((data < (Q1 - 1.5 * IQR)) | (data > (Q3 + 1.5 * IQR))).any(axis=1)]

X = data.drop('fare_amount', axis=1)
y = data['fare_amount']

# Normalize the data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Splitting data
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Fit the model
model = LinearRegression()
model.fit(X_train, y_train)

# prediction
y_pred = model.predict(X_test)

# performance metrics
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)
print(f'Mean Squared Error: {mse}')
print(f'R-squared: {r2}')

# Visualization of solution
plt.scatter(y_test, y_pred)
plt.xlabel('Actual Fare')
plt.ylabel('Predicted Fare')
plt.title('Actual vs. Predicted Fare')
plt.show()

"""The transparency in the fare amount can be provided by considering the features such as trip distance,pickup time,passenger_count from this model by a mean squared error of 14.94 and r squared as 0.04"""